# Generated by Django 3.1.4 on 2021-01-23 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/')),
                ('title', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('size', models.SlugField(max_length=4)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('availabilty', models.BooleanField()),
                ('gender', models.BooleanField()),
                ('date', models.DateField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cat')),
            ],
        ),
    ]
