# Generated by Django 3.1.4 on 2021-02-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_orderitem_payment_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='slug',
            field=models.SlugField(default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='types',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='types',
            name='size',
            field=models.CharField(max_length=4),
        ),
    ]
